org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.162
neo_version_range=[21.1.162,)
loader_version_range=[1,)

## Mod Properties
mod_id=rsinfinitybooster
mod_name=RSInfinityBooster
mod_license=GNU Lesser General Public License
mod_version=1.0.0
mod_group_id=uk.co.hexeption.rsinfinitybooster
mod_authors=Hexeption
mod_description=Adds Infinite Range Card and Dimension Card to Refine Storage
