name: Dev-Builds
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:17-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1.0.3
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build curseforge modrinth
        env:
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: Builds
          path: build/libs/*.jar
