name: Dev-Builds
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build publishCurseForge modrinth
        env:
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: Builds
          path: build/libs/*.jar
